/* Generated by GOB (v2.0.16)   (do not edit directly) */



/*
 * Copyright © 2009  Red Hat, Inc. All rights reserved.
 * Copyright © 2009  Ding-Yi Chen <dchen at redhat.com>
 *
 *  This file is part of MakerDialog.
 *
 *  MakerDialog is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  MakerDialog is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with MakerDialog.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <stdlib.h>
#include <strings.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <locale.h>
#include "../MakerDialog.h"
#include "../MakerDialogUiGtk.h"

#line 3 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
#line 35 "maker-dialog-gtk-private.h"
#ifndef __MAKER_DIALOG_GTK_PRIVATE_H__
#define __MAKER_DIALOG_GTK_PRIVATE_H__

#include "maker-dialog-gtk.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _MakerDialogGtkPrivate {
#line 69 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	MakerDialog * mDialog;
#line 70 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	GHashTable * widgetTable;
#line 72 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	GHashTable * comboboxValuesTable;
#line 52 "maker-dialog-gtk-private.h"
};
#line 270 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_outbox_and_label_new	(MakerDialogGtk * self, GtkWidget * widget, MakerDialogPropertyContext * ctx, MakerDialogGtkPlacement labelPlacement);
#line 56 "maker-dialog-gtk-private.h"
#line 318 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_check_button_new	(MakerDialogGtk * self, MakerDialogPropertyContext * ctx);
#line 59 "maker-dialog-gtk-private.h"
#line 327 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_color_button_new	(MakerDialogGtk * self, MakerDialogPropertyContext * ctx);
#line 62 "maker-dialog-gtk-private.h"
#line 336 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_combo_box_new	(MakerDialogGtk * self, MakerDialogPropertyContext * ctx);
#line 65 "maker-dialog-gtk-private.h"
#line 384 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_entry_new	(MakerDialogGtk * self, MakerDialogPropertyContext * ctx);
#line 68 "maker-dialog-gtk-private.h"
#line 398 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_radio_buttons_new	(MakerDialogGtk * self, MakerDialogPropertyContext * ctx);
#line 71 "maker-dialog-gtk-private.h"
#line 432 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_spin_button_new	(MakerDialogGtk * self, MakerDialogPropertyContext * ctx);
#line 74 "maker-dialog-gtk-private.h"
#line 443 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
gboolean 	maker_dialog_gtk_add_property_ui	(MakerDialogGtk * self, MakerDialogPropertyContext * ctx);
#line 77 "maker-dialog-gtk-private.h"
#line 520 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 	maker_dialog_gtk_align_labels	(MakerDialogGtk * self, const gchar * pageName, MakerDialogAlignment * labelAlignment);
#line 80 "maker-dialog-gtk-private.h"
#line 736 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_get_page_vbox	(MakerDialogGtk * self, const gchar * pageName);
#line 83 "maker-dialog-gtk-private.h"
#line 743 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_get_base_vbox	(MakerDialogGtk * self, MakerDialogPropertySpec * spec);
#line 86 "maker-dialog-gtk-private.h"
#line 751 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 	maker_dialog_gtk_widget_register	(MakerDialogGtk * self, GtkWidget * widget, const gchar * widget_label, const gchar * subLabel, const gchar * widget_type, gint serial);
#line 89 "maker-dialog-gtk-private.h"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
