/* Generated by GOB (v2.0.14)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */


#line 3 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"

/*
 * Copyright © 2009  Red Hat, Inc. All rights reserved.
 * Copyright © 2009  Ding-Yi Chen <dchen at redhat.com>
 *
 *  This file is part of MakerDialog.
 *
 *  MakerDialog is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  MakerDialog is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with MakerDialog.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <stdlib.h>
#include <strings.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <locale.h>
#include "../MakerDialog.h"
#include "../MakerDialogUiGtk.h"

#line 37 "maker-dialog-gtk.c"
#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 14

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "maker-dialog-gtk.h"

#include "maker-dialog-gtk-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */
static const GEnumValue _makerdialog_gtk_placement_values[] = {
	{ MAKER_DIALOG_GTK_PLACEMENT_NONE, (char *)"MAKER_DIALOG_GTK_PLACEMENT_NONE", (char *)"none" },
	{ MAKER_DIALOG_GTK_PLACEMENT_LEFT, (char *)"MAKER_DIALOG_GTK_PLACEMENT_LEFT", (char *)"left" },
	{ MAKER_DIALOG_GTK_PLACEMENT_RIGHT, (char *)"MAKER_DIALOG_GTK_PLACEMENT_RIGHT", (char *)"right" },
	{ MAKER_DIALOG_GTK_PLACEMENT_TOP, (char *)"MAKER_DIALOG_GTK_PLACEMENT_TOP", (char *)"top" },
	{ MAKER_DIALOG_GTK_PLACEMENT_BOTTOM, (char *)"MAKER_DIALOG_GTK_PLACEMENT_BOTTOM", (char *)"bottom" },
	{ MAKER_DIALOG_GTK_PLACEMENT_IN_FRAME, (char *)"MAKER_DIALOG_GTK_PLACEMENT_IN_FRAME", (char *)"in-frame" },
	{ 0, NULL, NULL }
};

GType
makerdialog_gtk_placement_get_type (void)
{
	static GType type = 0;
	if ___GOB_UNLIKELY(type == 0)
		type = g_enum_register_static ("MakerDialogGtkPlacement", _makerdialog_gtk_placement_values);
	return type;
}


#line 53 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"

#ifndef STRING_BUFFER_SIZE_DEFAULT
#define STRING_BUFFER_SIZE_DEFAULT 200
#endif

#include "../config.h"
#include "MakerDialogGtk-def.c"

#line 86 "maker-dialog-gtk.c"
/* self casting macros */
#define SELF(x) MAKER_DIALOG_GTK(x)
#define SELF_CONST(x) MAKER_DIALOG_GTK_CONST(x)
#define IS_SELF(x) MAKER_IS_DIALOG_GTK(x)
#define TYPE_SELF MAKER_TYPE_DIALOG_GTK
#define SELF_CLASS(x) MAKER_DIALOG_GTK_CLASS(x)

#define SELF_GET_CLASS(x) MAKER_DIALOG_GTK_GET_CLASS(x)

/* self typedefs */
typedef MakerDialogGtk Self;
typedef MakerDialogGtkClass SelfClass;

/* here are local prototypes */
static void maker_dialog_gtk_class_init (MakerDialogGtkClass * c) G_GNUC_UNUSED;
static void maker_dialog_gtk_init (MakerDialogGtk * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkDialogClass *parent_class = NULL;

/* Short form macros */
#define self_new maker_dialog_gtk_new
#define self_new_full maker_dialog_gtk_new_full
#define self_outbox_and_label_new maker_dialog_gtk_outbox_and_label_new
#define self_check_button_new maker_dialog_gtk_check_button_new
#define self_color_button_new maker_dialog_gtk_color_button_new
#define self_combo_box_new maker_dialog_gtk_combo_box_new
#define self_entry_new maker_dialog_gtk_entry_new
#define self_radio_buttons_new maker_dialog_gtk_radio_buttons_new
#define self_spin_button_new maker_dialog_gtk_spin_button_new
#define self_add_property_ui maker_dialog_gtk_add_property_ui
#define self_align_labels maker_dialog_gtk_align_labels
#define self_destroy maker_dialog_gtk_destroy
#define self_get_widget_value maker_dialog_gtk_get_widget_value
#define self_set_widget_value maker_dialog_gtk_set_widget_value
#define self_widget_control maker_dialog_gtk_widget_control
#define self_get_widget maker_dialog_gtk_get_widget
#define self_get_widget_full maker_dialog_gtk_get_widget_full
#define self_get_widget_by_id maker_dialog_gtk_get_widget_by_id
#define self_get_page_vbox maker_dialog_gtk_get_page_vbox
#define self_get_base_vbox maker_dialog_gtk_get_base_vbox
#define self_widget_register maker_dialog_gtk_widget_register
GType
maker_dialog_gtk_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (MakerDialogGtkClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) maker_dialog_gtk_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (MakerDialogGtk),
			0 /* n_preallocs */,
			(GInstanceInitFunc) maker_dialog_gtk_init,
			NULL
		};

		type = g_type_register_static (GTK_TYPE_DIALOG, "MakerDialogGtk", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((MakerDialogGtk *)g_object_new(maker_dialog_gtk_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static MakerDialogGtk * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static MakerDialogGtk *
GET_NEW_VARG (const char *first, ...)
{
	MakerDialogGtk *ret;
	va_list ap;
	va_start (ap, first);
	ret = (MakerDialogGtk *)g_object_new_valist (maker_dialog_gtk_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::finalize"
	MakerDialogGtk *self G_GNUC_UNUSED = MAKER_DIALOG_GTK (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 67 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	if(self->dialog_notebook) { gtk_widget_destroy ((gpointer) self->dialog_notebook); self->dialog_notebook = NULL; }
#line 182 "maker-dialog-gtk.c"
#line 71 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	if(self->_priv->widgetTable) { g_hash_table_destroy ((gpointer) self->_priv->widgetTable); self->_priv->widgetTable = NULL; }
#line 185 "maker-dialog-gtk.c"
#line 73 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	if(self->_priv->comboboxValuesTable) { g_hash_table_destroy ((gpointer) self->_priv->comboboxValuesTable); self->_priv->comboboxValuesTable = NULL; }
#line 188 "maker-dialog-gtk.c"
}
#undef __GOB_FUNCTION__

static void 
maker_dialog_gtk_class_init (MakerDialogGtkClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	g_type_class_add_private(c,sizeof(MakerDialogGtkPrivate));

	parent_class = g_type_class_ref (GTK_TYPE_DIALOG);

	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__
#line 75 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
static void 
maker_dialog_gtk_init (MakerDialogGtk * self G_GNUC_UNUSED)
#line 208 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::init"
	self->_priv = G_TYPE_INSTANCE_GET_PRIVATE(self,MAKER_TYPE_DIALOG_GTK,MakerDialogGtkPrivate);
#line 53 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	self->vbox_homogeneous = FALSE;
#line 214 "maker-dialog-gtk.c"
#line 53 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	self->hbox_spacing = 2;
#line 217 "maker-dialog-gtk.c"
#line 53 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	self->vbox_spacing = 2;
#line 220 "maker-dialog-gtk.c"
#line 53 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	self->dialog_notebook = NULL;
#line 223 "maker-dialog-gtk.c"
#line 53 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	self->_priv->mDialog = NULL;
#line 226 "maker-dialog-gtk.c"
#line 70 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	self->_priv->widgetTable = g_hash_table_new_full(g_str_hash,g_str_equal, g_free, NULL);
#line 229 "maker-dialog-gtk.c"
#line 72 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	self->_priv->comboboxValuesTable = g_hash_table_new_full(g_str_hash,g_str_equal, NULL, g_string_chunk_free_wrap);
#line 232 "maker-dialog-gtk.c"
}
#undef __GOB_FUNCTION__



#line 78 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
MakerDialogGtk * 
maker_dialog_gtk_new (void)
#line 241 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::new"
{
#line 78 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	Self *self = GET_NEW;
	return self;
    }}
#line 250 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 83 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
MakerDialogGtk * 
maker_dialog_gtk_new_full (MakerDialogUi * dlgUi, GtkWindow * parentWindow, gboolean modal)
#line 256 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::new_full"
{
#line 83 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	MAKER_DIALOG_DEBUG_MSG(2,"[I2] Gtk:new_full(-,-,%s)",(modal)? "TRUE":"FALSE");
	Self *self = GET_NEW;
	gtk_window_set_title(GTK_WINDOW(self),dlgUi->mDialog->title);
	gtk_window_set_modal (GTK_WINDOW(self), modal);
	if (parentWindow){
    	    gtk_window_set_transient_for(GTK_WINDOW(self),parentWindow);
	    gtk_window_set_destroy_with_parent (GTK_WINDOW(self), TRUE);
	}else{
	    gtk_window_set_destroy_with_parent (GTK_WINDOW(self), FALSE);
	}
	gtk_window_set_type_hint (GTK_WINDOW(self), GDK_WINDOW_TYPE_HINT_DIALOG);
	self->_priv->mDialog=dlgUi->mDialog;

	if (self->_priv->mDialog->buttonSpecs){
	    gint i;
	    for(i=0;self->_priv->mDialog->buttonSpecs[i].responseId!=MAKER_DIALOG_RESPONSE_NIL;i++){
		gchar *buttonText=NULL;
		if (self->_priv->mDialog->buttonSpecs[i].buttonText){
		    buttonText=(gchar *) self->_priv->mDialog->buttonSpecs[i].buttonText;
		}else{

		    switch(self->_priv->mDialog->buttonSpecs[i].responseId){
			case MAKER_DIALOG_RESPONSE_REJECT:
			case MAKER_DIALOG_RESPONSE_ACCEPT:
			case MAKER_DIALOG_RESPONSE_DELETE_EVENT:
			    break;
			case MAKER_DIALOG_RESPONSE_OK:
			    buttonText=GTK_STOCK_OK;
			    break;
			case MAKER_DIALOG_RESPONSE_CANCEL:
			    buttonText=GTK_STOCK_CANCEL;
			    break;
			case MAKER_DIALOG_RESPONSE_CLOSE:
			    buttonText=GTK_STOCK_CLOSE;
			    break;
			case MAKER_DIALOG_RESPONSE_YES:
			    buttonText=GTK_STOCK_YES;
			    break;
			case MAKER_DIALOG_RESPONSE_NO:
			    buttonText=GTK_STOCK_NO;
			    break;
			case MAKER_DIALOG_RESPONSE_APPLY:
			    buttonText=GTK_STOCK_APPLY;
			    break;
			case MAKER_DIALOG_RESPONSE_FILE:
			    buttonText=GTK_STOCK_FILE;
			    break;
			case MAKER_DIALOG_RESPONSE_NEW:
			    buttonText=GTK_STOCK_NEW;
			    break;
			case MAKER_DIALOG_RESPONSE_OPEN:
			    buttonText=GTK_STOCK_OPEN;
			    break;
			case MAKER_DIALOG_RESPONSE_SAVE:
			    buttonText=GTK_STOCK_SAVE;
			    break;
			case MAKER_DIALOG_RESPONSE_SAVE_AS:
			    buttonText=GTK_STOCK_SAVE_AS;
			    break;
			case MAKER_DIALOG_RESPONSE_PRINT:
			    buttonText=GTK_STOCK_PRINT;
			    break;
			case MAKER_DIALOG_RESPONSE_QUIT:
			    buttonText=GTK_STOCK_QUIT;
			    break;
			case MAKER_DIALOG_RESPONSE_EDIT:
			    buttonText=GTK_STOCK_EDIT;
			    break;
			case MAKER_DIALOG_RESPONSE_UNDO:
			    buttonText=GTK_STOCK_UNDO;
			    break;
			case MAKER_DIALOG_RESPONSE_REDO:
			    buttonText=GTK_STOCK_REDO;
			    break;
			case MAKER_DIALOG_RESPONSE_REFRESH:
			    buttonText=GTK_STOCK_REFRESH;
			    break;
			case MAKER_DIALOG_RESPONSE_CUT:
			    buttonText=GTK_STOCK_CUT;
			    break;
			case MAKER_DIALOG_RESPONSE_COPY:
			    buttonText=GTK_STOCK_COPY;
			    break;
			case MAKER_DIALOG_RESPONSE_PASTE:
			    buttonText=GTK_STOCK_PASTE;
			    break;
			case MAKER_DIALOG_RESPONSE_SELECT_ALL:
			    buttonText=GTK_STOCK_SELECT_ALL;
			    break;
			case MAKER_DIALOG_RESPONSE_FIND:
			    buttonText=GTK_STOCK_FIND;
			    break;
			case MAKER_DIALOG_RESPONSE_FIND_AND_REPLACE:
			    buttonText=GTK_STOCK_FIND_AND_REPLACE;
			    break;
			case MAKER_DIALOG_RESPONSE_HELP:
			    buttonText=GTK_STOCK_HELP;
			    break;
			case MAKER_DIALOG_RESPONSE_GOTO_TOP:
			    buttonText=GTK_STOCK_GOTO_TOP;
			    break;
			case MAKER_DIALOG_RESPONSE_GOTO_BOTTOM:
			    buttonText=GTK_STOCK_GOTO_BOTTOM;
			    break;
			case MAKER_DIALOG_RESPONSE_GOTO_FIRST:
			    buttonText=GTK_STOCK_GOTO_FIRST;
			    break;
			case MAKER_DIALOG_RESPONSE_GOTO_LAST:
			    buttonText=GTK_STOCK_GOTO_LAST;
			    break;
			case MAKER_DIALOG_RESPONSE_GO_UP:
			    buttonText=GTK_STOCK_GO_UP;
			    break;
			case MAKER_DIALOG_RESPONSE_GO_DOWN:
			    buttonText=GTK_STOCK_GO_DOWN;
			    break;
			case MAKER_DIALOG_RESPONSE_GO_BACK:
			    buttonText=GTK_STOCK_GO_BACK;
			    break;
			case MAKER_DIALOG_RESPONSE_GO_FORWARD:
			    buttonText=GTK_STOCK_GO_FORWARD;
			    break;
			default:
			    break;
		    }
		}
		g_assert(buttonText);
		GtkWidget *button=gtk_dialog_add_button(GTK_DIALOG(self),_(buttonText),self->_priv->mDialog->buttonSpecs[i].responseId);
		self_widget_register(self, button, buttonText, NULL, "button",-1);
	    }
	}

	GNode *pageNode=g_node_first_child(self->_priv->mDialog->pageRoot);
	g_assert(pageNode);

	if ((strcmp((gchar *)pageNode->data,MAKER_DIALOG_PAGE_UNNAMED)==0 && g_node_n_children(self->_priv->mDialog->pageRoot)<=1)){
	    /* No notebook page. */
	    self_widget_register(self, GTK_DIALOG(self)->vbox, MAKER_DIALOG_PAGE_UNNAMED, NULL, "box", -1);

	    /* Add properties */
	    maker_dialog_page_foreach_property(self->_priv->mDialog, (gchar *)pageNode->data, maker_dialog_gtk_construct_ui_groupFunc, (gpointer) self,
		    maker_dialog_gtk_construct_ui_propFunc, (gpointer) self);
	}else{
	    /* Add notebook pages */
	    if (!self->dialog_notebook){
		self->dialog_notebook=gtk_notebook_new();
		gtk_box_pack_start (GTK_BOX(GTK_DIALOG(self)->vbox), self->dialog_notebook, TRUE, TRUE, 0);
	    }
	    for(; pageNode!=NULL; pageNode=g_node_next_sibling (pageNode)){
		gchar *pageName=(gchar *) pageNode->data;
		GtkWidget *label=gtk_label_new(_(pageName));
		self_widget_register(self, label, pageName, NULL, "label", -1);
		GtkWidget *vbox=gtk_vbox_new(self->vbox_homogeneous,self->vbox_spacing);
		self_widget_register(self, vbox, pageName, NULL, "box", -1);
		gtk_notebook_append_page (GTK_NOTEBOOK(self->dialog_notebook), vbox,label);
		/* Add properties */
		maker_dialog_page_foreach_property(self->_priv->mDialog, (gchar *)pageNode->data, maker_dialog_gtk_construct_ui_groupFunc, (gpointer) self,
			maker_dialog_gtk_construct_ui_propFunc, (gpointer) self);
	    }
	}

	/* Align labels */
	if (self->dialog_notebook){
	    for(pageNode=g_node_first_child(self->_priv->mDialog->pageRoot); pageNode!=NULL; pageNode=g_node_next_sibling (pageNode)){
		gchar *pageName=(gchar *) pageNode->data;
		self_align_labels(self, pageName, &self->_priv->mDialog->labelAlignment);
	    }
	}else{
	    /* No notebook page. */
	    self_align_labels(self, NULL, &self->_priv->mDialog->labelAlignment);
	}

//        if (self->_priv->mDialog->maxSizeInPixel->width>0 && self->_priv->mDialog->maxSizeInPixel->height>0){
//            gtk_widget_set_size_request (GTK_WIDGET(self), self->_priv->mDialog->maxSizeInPixel->width,self->_priv->mDialog->maxSizeInPixel->height);
//        }
	/* Perform control rules */
	maker_dialog_foreach_property(self->_priv->mDialog, maker_dialog_gtk_each_property_apply_control, self);


	return self;
    }}
#line 443 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 270 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_outbox_and_label_new (MakerDialogGtk * self, GtkWidget * widget, MakerDialogPropertyContext * ctx, MakerDialogGtkPlacement labelPlacement)
#line 449 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::outbox_and_label_new"
#line 270 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 270 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 456 "maker-dialog-gtk.c"
{
#line 270 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	GtkWidget *box=NULL;
	switch(labelPlacement){
	    case MAKER_DIALOG_GTK_PLACEMENT_TOP:
	    case MAKER_DIALOG_GTK_PLACEMENT_BOTTOM:
	    case MAKER_DIALOG_GTK_PLACEMENT_IN_FRAME:
		box=gtk_vbox_new(FALSE,self->vbox_spacing);
 		break;
	    case MAKER_DIALOG_GTK_PLACEMENT_LEFT:
	    case MAKER_DIALOG_GTK_PLACEMENT_RIGHT:
		box=gtk_hbox_new(FALSE,self->hbox_spacing);
		break;
	    default:
		break;
	}
	if (box){
	    self_widget_register(self, box, ctx->spec->key, NULL, "box",-1);
	    GtkWidget *label=gtk_label_new(_(ctx->spec->label));
	    self_widget_register(self, label, ctx->spec->key, NULL, "label",-1);
	    if (labelPlacement==MAKER_DIALOG_GTK_PLACEMENT_IN_FRAME){
		gtk_frame_set_label_widget(GTK_FRAME(widget),label);
	    }
#ifdef HAVE_GTK_WIDGET_SET_TOOLTIP_TEXT
	    if (ctx->spec->tooltip){
		gtk_widget_set_tooltip_text (label,_(ctx->spec->tooltip));
	    }
#endif
	    switch(labelPlacement){
		case MAKER_DIALOG_GTK_PLACEMENT_TOP:
		case MAKER_DIALOG_GTK_PLACEMENT_LEFT:
		    gtk_box_pack_start (GTK_BOX(box), label, FALSE, FALSE, 0);
		    gtk_box_pack_start (GTK_BOX(box), widget, FALSE, FALSE, 0);
		    break;
		case MAKER_DIALOG_GTK_PLACEMENT_BOTTOM:
		case MAKER_DIALOG_GTK_PLACEMENT_RIGHT:
		    gtk_box_pack_end (GTK_BOX(box), label, FALSE, FALSE, 0);
		    gtk_box_pack_end (GTK_BOX(box), widget, FALSE, FALSE, 0);
		    break;
		case MAKER_DIALOG_GTK_PLACEMENT_IN_FRAME:
		    gtk_box_pack_end (GTK_BOX(box), widget, FALSE, FALSE, 0);
		    break;
		default:
		    break;
	    }
	}
	return box;
    }}
#line 506 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 318 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_check_button_new (MakerDialogGtk * self, MakerDialogPropertyContext * ctx)
#line 512 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::check_button_new"
#line 318 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 318 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 519 "maker-dialog-gtk.c"
{
#line 318 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	GtkWidget *widget = gtk_check_button_new();
	self_widget_register(self, widget, ctx->spec->key, NULL, NULL,-1);

	gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(widget),maker_dialog_value_get_boolean(ctx->value));
	g_signal_connect(widget, "toggled", G_CALLBACK(widget_event_wrap),ctx);
	return widget;
    }}
#line 530 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 327 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_color_button_new (MakerDialogGtk * self, MakerDialogPropertyContext * ctx)
#line 536 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::color_button_new"
#line 327 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 327 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 543 "maker-dialog-gtk.c"
{
#line 327 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	GdkColor color={0};
	MkdgValue_get_GdkColor(ctx->value, &color);
	GtkWidget *widget=gtk_color_button_new_with_color(&color);
	self_widget_register(self, widget, ctx->spec->key, NULL, NULL,-1);
	g_signal_connect(widget, "color-set", G_CALLBACK(widget_event_wrap),ctx);
	return widget;
    }}
#line 554 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 336 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_combo_box_new (MakerDialogGtk * self, MakerDialogPropertyContext * ctx)
#line 560 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::combo_box_new"
#line 336 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 336 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 567 "maker-dialog-gtk.c"
{
#line 336 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	GtkWidget *widget=NULL;
	GtkListStore *listStore=gtk_list_store_new(2, G_TYPE_STRING, G_TYPE_STRING);

	gint i;
	gint index=-1;
	gchar *listKey_curr=maker_dialog_property_to_string(ctx);
	GStringChunk *strChunk=g_string_chunk_new(STRING_BUFFER_SIZE_DEFAULT);
	g_hash_table_insert(self->_priv->comboboxValuesTable, (gpointer) ctx->spec->key, (gpointer) strChunk);

	for(i=0;ctx->spec->validValues[i]!=NULL;i++){
	    /* Add new item*/
	    gchar *listKey_tmp=maker_dialog_string_convert(ctx->spec->validValues[i], ctx->spec->valueType, ctx->spec->parseOption, ctx->spec->toStringFormat);
	    gchar *listKey=g_string_chunk_insert_const(strChunk, listKey_tmp);
	    g_free(listKey_tmp);

	    listStore_append(listStore, listKey, maker_dialog_gtk_get_translation_string(ctx->spec->validValues[i], ctx->spec));
	    if (strcmp(listKey_curr,listKey)==0){
		index=i;
	    }
	}
	if (index<0 && !(ctx->spec->flags & MAKER_DIALOG_PROPERTY_FLAG_FIXED_SET)){
	    listStore_prepend(listStore, listKey_curr, listKey_curr);
	    index=0;
	}
	g_free(listKey_curr);

	if (ctx->spec->flags & MAKER_DIALOG_PROPERTY_FLAG_FIXED_SET){
	    widget=gtk_combo_box_new_with_model (GTK_TREE_MODEL(listStore));
	    GtkCellRenderer *renderer = gtk_cell_renderer_text_new();
	    gtk_cell_layout_pack_start(GTK_CELL_LAYOUT(widget), renderer, FALSE);
	    gtk_cell_layout_set_attributes(GTK_CELL_LAYOUT(widget), renderer,
		    "text", 1,
		    NULL);
	    g_signal_connect(widget, "changed", G_CALLBACK(widget_event_wrap),ctx);
	}else{
	    widget=gtk_combo_box_entry_new_with_model (GTK_TREE_MODEL(listStore), 1);
	    g_signal_connect(widget, "changed", G_CALLBACK(on_combo_box_entry_change_wrap),ctx);
	    GtkWidget *entry=gtk_bin_get_child(GTK_BIN(widget));
	    g_signal_connect(entry, "activate", G_CALLBACK(widget_event_wrap),ctx);
	}

	self_widget_register(self, widget, ctx->spec->key, NULL, NULL, -1);
	gtk_combo_box_set_active(GTK_COMBO_BOX(widget),index);

	return widget;
    }}
#line 617 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 384 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_entry_new (MakerDialogGtk * self, MakerDialogPropertyContext * ctx)
#line 623 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::entry_new"
#line 384 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 384 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 630 "maker-dialog-gtk.c"
{
#line 384 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	GtkWidget *widget=gtk_entry_new();
	self_widget_register(self, widget, ctx->spec->key, NULL, NULL,-1);
	if (ctx->spec->max>=0){
	    gtk_entry_set_max_length(GTK_ENTRY(widget),ctx->spec->max);
	}
	gtk_entry_set_text(GTK_ENTRY(widget), maker_dialog_value_get_string(ctx->value));
	gtk_editable_set_editable (GTK_EDITABLE(widget),
		!(ctx->spec->flags & MAKER_DIALOG_PROPERTY_FLAG_FIXED_SET));

	g_signal_connect(widget, "activate", G_CALLBACK(widget_event_wrap),ctx);
	return widget;
    }}
#line 646 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 398 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_radio_buttons_new (MakerDialogGtk * self, MakerDialogPropertyContext * ctx)
#line 652 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::radio_buttons_new"
#line 398 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 398 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 659 "maker-dialog-gtk.c"
{
#line 398 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	GtkWidget *box=gtk_vbox_new(FALSE,self->vbox_spacing);
	self_widget_register(self, box, ctx->spec->key, NULL, "box",-1);
	GtkWidget *radio=NULL;
	GtkWidget *radioHead=NULL;
	gsize i;
	for(i=0;ctx->spec->validValues[i]!=NULL;i++){
	    const gchar *strPtr=maker_dialog_gtk_get_translation_string(ctx->spec->validValues[i], ctx->spec);
	    if (i==0){
		radio=radioHead=gtk_radio_button_new_with_label(NULL, strPtr);
		self_widget_register(self, radio, ctx->spec->key, NULL, NULL, -1);
	    }else{
		radio=gtk_radio_button_new_with_label_from_widget(GTK_RADIO_BUTTON(radioHead), strPtr);
		self_widget_register(self, radio, ctx->spec->key, NULL, NULL, i);
	    }
	    gtk_box_pack_start (GTK_BOX(box), radio, FALSE, FALSE, 0);
	    if (ctx->valueIndex==i){
		gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(radio), TRUE);
	    }else{
		gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(radio), FALSE);
	    }
	    g_signal_connect(radio, "toggled", G_CALLBACK(on_radioButton_toggled_wrap),ctx);
	}

	GtkWidget *widget=gtk_frame_new(_(ctx->spec->label));
	gtk_container_add(GTK_CONTAINER(widget), box);
#ifdef HAVE_GTK_WIDGET_SET_TOOLTIP_TEXT
	if (ctx->spec->tooltip){
	    gtk_widget_set_tooltip_text (widget,_(ctx->spec->tooltip));
	}
#endif
	return widget;
    }}
#line 695 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 432 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_spin_button_new (MakerDialogGtk * self, MakerDialogPropertyContext * ctx)
#line 701 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::spin_button_new"
#line 432 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 432 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 708 "maker-dialog-gtk.c"
{
#line 432 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	GtkAdjustment *gAdjust= GTK_ADJUSTMENT(gtk_adjustment_new (
		maker_dialog_value_to_double(ctx->value),
		ctx->spec->min, ctx->spec->max, ctx->spec->step, ctx->spec->step*10, 0.0));
	GtkWidget *widget = gtk_spin_button_new (gAdjust, ctx->spec->step, ctx->spec->decimalDigits);

	self_widget_register(self, widget, ctx->spec->key, NULL, NULL,-1);
	g_signal_connect(widget, "value-changed", G_CALLBACK(widget_event_wrap),ctx);
	return widget;
    }}
#line 721 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 443 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
gboolean 
maker_dialog_gtk_add_property_ui (MakerDialogGtk * self, MakerDialogPropertyContext * ctx)
#line 727 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::add_property_ui"
#line 443 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 443 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (gboolean )0);
#line 734 "maker-dialog-gtk.c"
{
#line 443 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	MAKER_DIALOG_DEBUG_MSG(3,"[I3] Gtk:add_property_ui(%s,-) hasValue=%s",ctx->spec->key,
	       	(ctx->flags & MAKER_DIALOG_PROPERTY_CONTEXT_FLAG_HAS_VALUE) ? "TRUE": "FALSE");

	GtkWidget *vbox=self_get_base_vbox(self, ctx->spec);
	g_assert(vbox);
	if (!(ctx->flags & MAKER_DIALOG_PROPERTY_CONTEXT_FLAG_HAS_VALUE)){
	    /* Use default value */
	    maker_dialog_property_set_default(ctx);
	}
	GtkWidget *widget=NULL;
	MakerDialogGtkPlacement labelPlacement=MAKER_DIALOG_GTK_PLACEMENT_LEFT;

	if (ctx->spec->validValues){
	    if (maker_dialog_has_all_flags(ctx->spec->flags, MAKER_DIALOG_PROPERTY_FLAG_PREFER_RADIO_BUTTONS| MAKER_DIALOG_PROPERTY_FLAG_FIXED_SET)){
		widget=self_radio_buttons_new(self, ctx);
		labelPlacement=MAKER_DIALOG_GTK_PLACEMENT_NONE;
	    }else{
		widget=self_combo_box_new(self, ctx);
	    }
	}else{
	    switch(ctx->spec->valueType){
		case MKDG_TYPE_BOOLEAN:
		    widget=self_check_button_new(self, ctx);
		    break;
		case MKDG_TYPE_INT:
		case MKDG_TYPE_UINT:
		case MKDG_TYPE_INT32:
		case MKDG_TYPE_UINT32:
		case MKDG_TYPE_INT64:
		case MKDG_TYPE_UINT64:
		case MKDG_TYPE_LONG:
		case MKDG_TYPE_ULONG:
		case MKDG_TYPE_FLOAT:
		case MKDG_TYPE_DOUBLE:
		    widget=self_spin_button_new(self, ctx);
		    break;
		case MKDG_TYPE_STRING:
		    widget=self_entry_new(self, ctx);
		    break;
		case MKDG_TYPE_COLOR:
		    widget=self_color_button_new(self, ctx);
		    break;
		default:
		    break;
	    }
	}

	if (!widget){
	    return FALSE;
	}
	GtkWidget *outbox= self_outbox_and_label_new(self, widget, ctx, labelPlacement);
	if (outbox){
	    gtk_box_pack_start (GTK_BOX(vbox), outbox, FALSE, FALSE, 2);
	}else{
	    /* Widget has its own box */
	    gtk_box_pack_start (GTK_BOX(vbox), widget, FALSE, FALSE, 2);
	}
	return TRUE;
    }}
#line 797 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

/**
 * maker_dialog_gtk_align_labels:
 * @self: A MakerDialogGtk.
 * @pageName: Name of notebook page to be apply, can be NULL.
 * @xalign: x align of labels. 0.0f for LEFT, 0.5f for CENTER, 1.0f for RIGHT.
 * @yalign: y align of labels. 0.0f for TOP, 0.5f for CENTER, 1.0f for BOTTOM.
 *
 * Align labels for better dialog appearance.
 *
 * Labels that associate with value setting widget are stretched into same width.
 * If @pageName is not NULL, only the labels in the page are stretched,
 * otherwise, all labels will be stretched.
 *
 * Moreover, the horizontal and vertical alignment can set by @xalign and @yalign, respectively.
 **/
#line 520 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 
maker_dialog_gtk_align_labels (MakerDialogGtk * self, const gchar * pageName, MakerDialogAlignment * labelAlignment)
#line 818 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::align_labels"
#line 520 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (self != NULL);
#line 520 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (MAKER_IS_DIALOG_GTK (self));
#line 825 "maker-dialog-gtk.c"
{
#line 520 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	gint currentMaxWidth=0;
	GNode *pageNode=maker_dialog_find_page_node(self->_priv->mDialog, (pageName)? pageName: MAKER_DIALOG_PAGE_UNNAMED);
	GNode *keyNode=NULL;
	GtkWidget *widget=NULL;
	GtkRequisition requisition;
	gchar *key=NULL;
	/* Calculate max label width */
	for(keyNode=g_node_first_child(pageNode); keyNode!=NULL; keyNode=g_node_next_sibling (keyNode)){
	    key=(gchar *)keyNode->data;
	    widget=self_get_widget_full(self, key, NULL, "label", -1);
	    if (widget){
		gtk_widget_size_request (widget,&requisition);
		currentMaxWidth=MAX(currentMaxWidth, requisition.width);
	    }
	}

	/* Set label width with currentMaxWidth */
	for(keyNode=g_node_first_child(pageNode); keyNode!=NULL; keyNode=g_node_next_sibling (keyNode)){
	    key=(gchar *)keyNode->data;
	    widget=self_get_widget_full(self, key, NULL, "label", -1);
	    if (widget){
		gtk_widget_set_size_request(widget, currentMaxWidth,-1);
		gtk_misc_set_alignment (GTK_MISC(widget),labelAlignment->x,labelAlignment->y);
	    }
	}
	gtk_widget_show_all(GTK_WIDGET(self));
    }}
#line 856 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 549 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 
maker_dialog_gtk_destroy (MakerDialogGtk * self)
#line 862 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::destroy"
#line 549 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (self != NULL);
#line 549 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (MAKER_IS_DIALOG_GTK (self));
#line 869 "maker-dialog-gtk.c"
{
#line 549 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	//gtk_widget_destroy (GTK_WIDGET(self));
	g_object_unref (G_OBJECT(self));
    }}
#line 876 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 554 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
MkdgValue * 
maker_dialog_gtk_get_widget_value (MakerDialogGtk * self, const gchar * key)
#line 882 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::get_widget_value"
#line 554 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (MkdgValue * )0);
#line 554 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (MkdgValue * )0);
#line 889 "maker-dialog-gtk.c"
{
#line 554 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	MAKER_DIALOG_DEBUG_MSG(3,"[I3] Gtk:get_widget_value(%s)",key);
	MakerDialogPropertyContext *ctx=maker_dialog_get_property_context(self->_priv->mDialog,key);
	if (!ctx){
	    /* Not found */
	    return NULL;
	}
	GtkWidget *widget=self_get_widget(self,key);
	if (!widget){
	    return NULL;
	}
	MkdgValue *value=maker_dialog_value_new(ctx->spec->valueType, NULL);
	if (ctx->spec->valueType ==MKDG_TYPE_COLOR){
	    GdkColor color;
	    gtk_color_button_get_color (GTK_COLOR_BUTTON(widget),&color);
	    MkdgValue_set_GdkColor(value, &color);
	} else if (ctx->spec->validValues){
	    if (maker_dialog_has_all_flags(ctx->spec->flags, MAKER_DIALOG_PROPERTY_FLAG_PREFER_RADIO_BUTTONS| MAKER_DIALOG_PROPERTY_FLAG_FIXED_SET)){
		gint iCount;
		for (iCount=0;ctx->spec->validValues[iCount]!=NULL;iCount++){}

		GSList *sList=gtk_radio_button_get_group(GTK_RADIO_BUTTON(widget));
		/* The head of list is the last one add to radio button */

		gint i=0,iSet=-1;
		while(sList){

		    if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(sList->data))){
			iSet= iCount-1-i;
			break;
		    }
		    sList=g_slist_next(sList);
		    i++;
		}
		MAKER_DIALOG_DEBUG_MSG(5,"[I5] Gtk:get_widget_value(-,%s) item %d activated", key, iSet);
		if (iSet>=0){
		    maker_dialog_value_from_string(value, ctx->spec->validValues[iSet], ctx->spec->parseOption);
		}else{
		    maker_dialog_value_free(value);
		    return NULL;
		}
	    }else{
		GValue valTmp={0};
		g_assert(combo_get_active_value(GTK_COMBO_BOX(widget), &valTmp));
		maker_dialog_value_from_string(value, g_value_get_string(&valTmp), ctx->spec->parseOption);
		g_value_unset(&valTmp);
	    }
	}else{
	    switch(ctx->spec->valueType){
		case MKDG_TYPE_BOOLEAN:
		    maker_dialog_value_set_boolean(value, gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON(widget)));
		    break;
		case MKDG_TYPE_INT:
		case MKDG_TYPE_UINT:
		case MKDG_TYPE_INT32:
		case MKDG_TYPE_UINT32:
		case MKDG_TYPE_INT64:
		case MKDG_TYPE_UINT64:
		case MKDG_TYPE_LONG:
		case MKDG_TYPE_ULONG:
		case MKDG_TYPE_FLOAT:
		case MKDG_TYPE_DOUBLE:
		    maker_dialog_value_from_double(value, gtk_spin_button_get_value (GTK_SPIN_BUTTON(widget)));
		    break;
		case MKDG_TYPE_STRING:
		    maker_dialog_value_set_string(value, (gchar *) gtk_entry_get_text (GTK_ENTRY(widget)));
		    break;
		default:
		    break;
	    }
	}
	return value;
    }}
#line 965 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

/**
 * maker_dialog_gtk_set_widget_value:
 * @self: A MakerDialogGtk.
 * @key: The key of a property.
 * @value: Value to be shown in widget.
 *
 * Set value for widget display.
 * However, the property value is not set.
 * Use apply_widget_value() to do it.
 * @see_also: apply_widget_value()
 **/
#line 639 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 
maker_dialog_gtk_set_widget_value (MakerDialogGtk * self, const gchar * key, MkdgValue * value)
#line 982 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::set_widget_value"
#line 639 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (self != NULL);
#line 639 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (MAKER_IS_DIALOG_GTK (self));
#line 989 "maker-dialog-gtk.c"
{
#line 639 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	int index;
	MAKER_DIALOG_DEBUG_MSG(4,"[I4] Gtk:set_widget_value()");
	MakerDialogPropertyContext *ctx=maker_dialog_get_property_context(self->_priv->mDialog,key);
	if (!ctx){
	    /* Not found */
	    return;
	}
	GtkWidget *widget=self_get_widget(self,key);
	if (ctx->spec->valueType ==MKDG_TYPE_COLOR){
	    GdkColor color;
	    MkdgValue_get_GdkColor(value, &color);
	    gtk_color_button_set_color (GTK_COLOR_BUTTON(widget),&color);
	} else if (ctx->spec->validValues){
	    if (maker_dialog_has_all_flags(ctx->spec->flags,
			MAKER_DIALOG_PROPERTY_FLAG_PREFER_RADIO_BUTTONS| MAKER_DIALOG_PROPERTY_FLAG_FIXED_SET)){
		gint iCount;
		for (iCount=0;ctx->spec->validValues[iCount]!=NULL;iCount++){}

		gint i=iCount-1;
		GSList *sList=gtk_radio_button_get_group(GTK_RADIO_BUTTON(widget));
		/* The head of list is the last one add to radio button */
		MkdgValue *mValue=maker_dialog_value_new(ctx->spec->valueType, NULL);
		while(sList){
		    maker_dialog_value_from_string(mValue, ctx->spec->validValues[i], ctx->spec->parseOption);
		    gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(sList->data),
			    (maker_dialog_value_compare(mValue, value, ctx->spec->compareOption)==0) ? TRUE: FALSE );
		    sList=g_slist_next(sList);
		    i--;
		}
		maker_dialog_value_free(mValue);
	    }else{
		index=combo_find_value_index(GTK_COMBO_BOX(widget), value, ctx->spec);
		gtk_combo_box_set_active (GTK_COMBO_BOX(widget),index);
	    }
	}else{
	    switch(ctx->spec->valueType){
		case MKDG_TYPE_BOOLEAN:
		    gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON(widget),maker_dialog_value_get_boolean(value));
		    break;
		case MKDG_TYPE_INT:
		case MKDG_TYPE_UINT:
		case MKDG_TYPE_INT32:
		case MKDG_TYPE_UINT32:
		case MKDG_TYPE_INT64:
		case MKDG_TYPE_UINT64:
		case MKDG_TYPE_LONG:
		case MKDG_TYPE_ULONG:
		case MKDG_TYPE_FLOAT:
		case MKDG_TYPE_DOUBLE:
		    gtk_spin_button_set_value (GTK_SPIN_BUTTON(widget), maker_dialog_value_to_double(value));
		    break;
		case MKDG_TYPE_STRING:
		    gtk_entry_set_text (GTK_ENTRY(widget), maker_dialog_value_get_string(value));
		    break;
		default:
		    break;
	    }
	}
    }}
#line 1052 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 700 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 
maker_dialog_gtk_widget_control (MakerDialogGtk * self, const gchar * key, MakerDialogWidgetControl control)
#line 1058 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::widget_control"
#line 700 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (self != NULL);
#line 700 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (MAKER_IS_DIALOG_GTK (self));
#line 1065 "maker-dialog-gtk.c"
{
#line 700 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	MAKER_DIALOG_DEBUG_MSG(6,"[I6] Gtk:widget_control( , %s, %d)",key, control);
	GtkWidget *widget=self_get_widget(self, key);
	GtkWidget *boxWidget=self_get_widget_full(self, key, NULL, "box", -1);
	GtkWidget *labelWidget=self_get_widget_full(self, key, NULL, "label", -1);
	if (control & MAKER_DIALOG_WIDGET_CONTROL_SHOW){
	    gtk_widget_show_all(boxWidget);
	}else if (control & MAKER_DIALOG_WIDGET_CONTROL_HIDE){
	    gtk_widget_hide_all(boxWidget);
	}
	if (control & MAKER_DIALOG_WIDGET_CONTROL_SENSITIVE){
	    gtk_widget_set_sensitive(widget, TRUE);
	    gtk_widget_set_sensitive(labelWidget, TRUE);
	}else if (control & MAKER_DIALOG_WIDGET_CONTROL_INSENSITIVE){
	    gtk_widget_set_sensitive(widget,FALSE);
	    gtk_widget_set_sensitive(labelWidget, FALSE);
	}
    }}
#line 1086 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 719 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_get_widget (MakerDialogGtk * self, const gchar * key)
#line 1092 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::get_widget"
#line 719 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 719 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 1099 "maker-dialog-gtk.c"
{
#line 719 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	return self_get_widget_full(self,key, NULL, NULL, -1);
    }}
#line 1105 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 723 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_get_widget_full (MakerDialogGtk * self, const gchar * widget_label, const gchar * subLabel, const gchar * widget_type, gint serial)
#line 1111 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::get_widget_full"
#line 723 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 723 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 1118 "maker-dialog-gtk.c"
{
#line 724 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	gchar *id=widget_gen_id(widget_label, subLabel, widget_type, serial);
	GtkWidget *widget=self_get_widget_by_id(self, id);
	g_free(id);
	return widget;
    }}
#line 1127 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 731 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_get_widget_by_id (MakerDialogGtk * self, const gchar * id)
#line 1133 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::get_widget_by_id"
#line 731 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 731 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 1140 "maker-dialog-gtk.c"
{
#line 731 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	MAKER_DIALOG_DEBUG_MSG(6,"[I6] Gtk:get_widget_by_id(%s)",id);
	return (GtkWidget *) g_hash_table_lookup (self->_priv->widgetTable, id);
    }}
#line 1147 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 736 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_get_page_vbox (MakerDialogGtk * self, const gchar * pageName)
#line 1153 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::get_page_vbox"
#line 736 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 736 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 1160 "maker-dialog-gtk.c"
{
#line 736 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	if (!maker_dialog_page_name_is_empty(pageName)){
	    return self_get_widget_full(self, pageName, NULL, "box", -1);
	}
	return self_get_widget_full(self, MAKER_DIALOG_PAGE_UNNAMED, NULL, "box", -1);
    }}
#line 1169 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 743 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 
maker_dialog_gtk_get_base_vbox (MakerDialogGtk * self, MakerDialogPropertySpec * spec)
#line 1175 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::get_base_vbox"
#line 743 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (self != NULL, (GtkWidget * )0);
#line 743 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_val_if_fail (MAKER_IS_DIALOG_GTK (self), (GtkWidget * )0);
#line 1182 "maker-dialog-gtk.c"
{
#line 743 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	if (!maker_dialog_group_name_is_empty(spec->groupName)){
	    return self_get_widget_full(self,
		    (maker_dialog_page_name_is_empty(spec->pageName))? NULL : spec->pageName, spec->groupName, "box", -1);
	}
	return self_get_page_vbox(self, spec->pageName);
    }}
#line 1192 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__

#line 751 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 
maker_dialog_gtk_widget_register (MakerDialogGtk * self, GtkWidget * widget, const gchar * widget_label, const gchar * subLabel, const gchar * widget_type, gint serial)
#line 1198 "maker-dialog-gtk.c"
{
#define __GOB_FUNCTION__ "Maker:Dialog:Gtk::widget_register"
#line 751 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (self != NULL);
#line 751 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	g_return_if_fail (MAKER_IS_DIALOG_GTK (self));
#line 1205 "maker-dialog-gtk.c"
{
#line 752 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
	
	gchar *id=widget_gen_id(widget_label, subLabel, widget_type, serial);
	g_hash_table_insert(self->_priv->widgetTable, id, widget);
	gtk_widget_set_name(widget, id);
	MAKER_DIALOG_DEBUG_MSG(6,"[I6] Gtk:widget_register(-,%s,%s) widget registered as %s",
		widget_label,(widget_type)? (widget_type) : "", id);
    }}
#line 1215 "maker-dialog-gtk.c"
#undef __GOB_FUNCTION__
