/* Generated by GOB (v2.0.16)   (do not edit directly) */



/*
 * Copyright © 2009  Red Hat, Inc. All rights reserved.
 * Copyright © 2009  Ding-Yi Chen <dchen at redhat.com>
 *
 *  This file is part of MakerDialog.
 *
 *  MakerDialog is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  MakerDialog is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with MakerDialog.  If not, see <http://www.gnu.org/licenses/>.
 */
#include <stdlib.h>
#include <strings.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <locale.h>
#include "../MakerDialog.h"
#include "../MakerDialogUiGtk.h"

#include <glib.h>
#include <glib-object.h>


/**
 * Gtk binding for MakerDialog.
 *
 * This module provides convenient function to build a Gtk dialog.
 */

#ifndef MAKER_DIALOG_GTK_GOB_H_
#define MAKER_DIALOG_GTK_GOB_H_



#endif /* MAKER_DIALOG_GTK_GOB_H_ */

#ifndef __MAKER_DIALOG_GTK_H__
#define __MAKER_DIALOG_GTK_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


typedef enum {
	MAKER_DIALOG_GTK_PLACEMENT_NONE,
	MAKER_DIALOG_GTK_PLACEMENT_LEFT,
	MAKER_DIALOG_GTK_PLACEMENT_RIGHT,
	MAKER_DIALOG_GTK_PLACEMENT_TOP,
	MAKER_DIALOG_GTK_PLACEMENT_BOTTOM,
	MAKER_DIALOG_GTK_PLACEMENT_IN_FRAME
} MakerDialogGtkPlacement;
#define MAKERDIALOG_TYPE_GTK_PLACEMENT makerdialog_gtk_placement_get_type()
GType makerdialog_gtk_placement_get_type (void) G_GNUC_CONST;


/*
 * Type checking and casting macros
 */
#define MAKER_TYPE_DIALOG_GTK	(maker_dialog_gtk_get_type())
#define MAKER_DIALOG_GTK(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), maker_dialog_gtk_get_type(), MakerDialogGtk)
#define MAKER_DIALOG_GTK_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), maker_dialog_gtk_get_type(), MakerDialogGtk const)
#define MAKER_DIALOG_GTK_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), maker_dialog_gtk_get_type(), MakerDialogGtkClass)
#define MAKER_IS_DIALOG_GTK(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), maker_dialog_gtk_get_type ())

#define MAKER_DIALOG_GTK_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), maker_dialog_gtk_get_type(), MakerDialogGtkClass)

/* Private structure type */
typedef struct _MakerDialogGtkPrivate MakerDialogGtkPrivate;

/*
 * Main object structure
 */
#ifndef __TYPEDEF_MAKER_DIALOG_GTK__
#define __TYPEDEF_MAKER_DIALOG_GTK__
typedef struct _MakerDialogGtk MakerDialogGtk;
#endif
struct _MakerDialogGtk {
	GtkDialog __parent__;
	/*< public >*/
	gboolean vbox_homogeneous;
	gint hbox_spacing;
	gint vbox_spacing;
	/*< private >*/
	GtkWidget * dialog_notebook; /* protected */
	MakerDialogGtkPrivate *_priv;
};

/*
 * Class definition
 */
typedef struct _MakerDialogGtkClass MakerDialogGtkClass;
struct _MakerDialogGtkClass {
	GtkDialogClass __parent__;
};


/*
 * Public methods
 */
GType	maker_dialog_gtk_get_type	(void) G_GNUC_CONST;
#line 78 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
MakerDialogGtk * 	maker_dialog_gtk_new	(void);
#line 118 "maker-dialog-gtk.h"
#line 83 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
MakerDialogGtk * 	maker_dialog_gtk_new_full	(MakerDialogUi * dlgUi,
					GtkWindow * parentWindow,
					gboolean modal);
#line 123 "maker-dialog-gtk.h"
#line 469 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 	maker_dialog_gtk_destroy	(MakerDialogGtk * self);
#line 126 "maker-dialog-gtk.h"
#line 474 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
MkdgValue * 	maker_dialog_gtk_get_widget_value	(MakerDialogGtk * self,
					const gchar * key);
#line 130 "maker-dialog-gtk.h"
#line 559 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 	maker_dialog_gtk_set_widget_value	(MakerDialogGtk * self,
					const gchar * key,
					MkdgValue * value);
#line 135 "maker-dialog-gtk.h"
#line 620 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
void 	maker_dialog_gtk_widget_control	(MakerDialogGtk * self,
					const gchar * key,
					MakerDialogWidgetControl control);
#line 140 "maker-dialog-gtk.h"
#line 639 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_get_widget	(MakerDialogGtk * self,
					const gchar * key);
#line 144 "maker-dialog-gtk.h"
#line 643 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_get_widget_full	(MakerDialogGtk * self,
					const gchar * widget_label,
					const gchar * subLabel,
					const gchar * widget_type,
					gint serial);
#line 151 "maker-dialog-gtk.h"
#line 651 "/home/dchen/MakerDialog/src/gtk/MakerDialogGtk.gob"
GtkWidget * 	maker_dialog_gtk_get_widget_by_id	(MakerDialogGtk * self,
					const gchar * id);
#line 155 "maker-dialog-gtk.h"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
